In [1]:
print("all ok")

all ok


In [3]:
import pandas as pd

data = pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})
data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer


In [7]:
BOW = CountVectorizer()
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [8]:
document_matrix = BOW.fit_transform(data["text"])
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

BOW - bag of words is tecnique of encoding . It converts words into vector based frequency of vacabulary in sentence. E.g In above sentence at 0 index frequence of ppl 1 , watch 1 , cricket 1 , watch 0 comment 0. in 2nd row cricket 2 watch 1, all other 0

In [11]:
BOW.vocabulary_

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

In [13]:
document_matrix[0].toarray()

array([[0, 1, 0, 1, 1]], dtype=int64)

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}
  cricket watch cricket

In [14]:
document_matrix[1].toarray()

array([[0, 2, 0, 0, 1]], dtype=int64)

In [16]:
bigram = CountVectorizer(ngram_range = (2,2))
bigram.vocabulary

In [17]:
bigram.fit_transform(data["text"])

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [19]:
bigram.vocabulary_

{'people watch': 4,
 'watch cricket': 5,
 'cricket watch': 1,
 'people give': 3,
 'give comment': 2,
 'cricket give': 0}

In [21]:
trigram = CountVectorizer(ngram_range = (3,3))
trigram.fit_transform(data["text"])
trigram.vocabulary_

{'people watch cricket': 3,
 'cricket watch cricket': 1,
 'people give comment': 2,
 'cricket give comment': 0}

This is preferred for encoding , as it helps to establish better context/semantic instead of bigram or trigram

In [24]:
mixgram = CountVectorizer(ngram_range = (1,3))
mixgram.fit_transform(data["text"])
mixgram.vocabulary_

{'people': 8,
 'watch': 13,
 'cricket': 1,
 'people watch': 11,
 'watch cricket': 14,
 'people watch cricket': 12,
 'cricket watch': 4,
 'cricket watch cricket': 5,
 'give': 6,
 'comment': 0,
 'people give': 9,
 'give comment': 7,
 'people give comment': 10,
 'cricket give': 2,
 'cricket give comment': 3}

One hot encoding OHE

In [32]:
df = pd.DataFrame(data,columns = ["text"])
df

text
0   people watch cricket
1  cricket watch cricket
2    people give comment
3   cricket give comment

In [35]:
one_hot = df["text"].str.get_dummies(sep = '')
print("One-Hot Encoded DataFrame:\n", one_hot)


One-Hot Encoded DataFrame:
       a  c  e  g  h  i  k  l  m  n  o  p  r  t  v  w
0  1  1  1  1  0  1  1  1  1  0  0  1  1  1  1  0  1
1  1  1  1  1  0  1  1  1  0  0  0  0  0  1  1  0  1
2  1  0  1  1  1  0  1  0  1  1  1  1  1  0  1  1  0
3  1  0  1  1  1  0  1  1  0  1  1  1  0  1  1  1  0


TF * IDF - Started by Google in 2010 . Still used in indistry. TF - Term Frequence = no. of occurance of word in a sentence / total no. of word in sentence. IDF - Inverse Document Frequency  = log(Total number of sentence/ no of sentences with that word). Vector of each word = TF* IDF . TF denotes importance of word in a given sentence, IDF - uniqueness of word in corpus. Log - basically reduces the skewness/spread. If uniqueness is more, IDF is more and vice versa

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
tfidf = TfidfVectorizer()

In [38]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.49681612, 0.        , 0.61366674, 0.61366674],
       [0.        , 0.8508161 , 0.        , 0.        , 0.52546357],
       [0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.61366674, 0.49681612, 0.61366674, 0.        , 0.        ]])

In [39]:
tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])